name: GitHub Pages Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './mentalspace-ehr-frontend/package-lock.json'
      
      - name: Install Dependencies
        working-directory: ./mentalspace-ehr-frontend
        run: npm ci
      
      - name: Build
        working-directory: ./mentalspace-ehr-frontend
        run: npm run build
        env:
          VITE_API_URL: https://api.mentalspace-ehr.com
      
      - name: Configure Base Path
        working-directory: ./mentalspace-ehr-frontend/dist
        run: |
          # Create a .nojekyll file to prevent GitHub Pages from ignoring files that begin with an underscore
          touch .nojekyll
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: mentalspace-ehr-frontend/dist
          clean: true 